#CRIANDO UMA MATRIZ

In [4]:
a = ([1,2,3],[4,5,6])
a

([1, 2, 3], [4, 5, 6])

In [5]:
import numpy as np #importando

#CRIANDO UMA ARRAY

In [6]:
a = np.array(a)
a


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(a)

numpy.ndarray

In [8]:
#SHAPE - > Quantidade de linhas e colunas
a.shape

(2, 3)

In [9]:
#SIZE - > Quantidade de elementos da matriz
a.size

6

In [10]:
#NDIM Quantidade mínima daquela matriz
a.ndim

2

In [11]:
#Tipo de Dados armazenando na matriz
a.dtype.name

'int32'

In [12]:
#Quantidade de items
a.itemsize

4

In [13]:
#retorna o local da memória,onde a matriz está guardada
a.data

#CRIANDO ARRAYS

In [15]:
#USANDO VETOR
a = {1,2,3,4,5}
a

{1, 2, 3, 4, 5}

In [16]:
np.array(a)

array({1, 2, 3, 4, 5}, dtype=object)

In [17]:
b = ({1,2,3},{4,5,6})
b

({1, 2, 3}, {4, 5, 6})

In [18]:
np.array(b)

array([{1, 2, 3}, {4, 5, 6}], dtype=object)

In [20]:
#criando uma matriz apenas de zeros ... segue o mesmo raciocínio caso fosse com 1 -> np.ones
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#EMPTY ->  retorna uma matriz vazia
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#ARANGE ->  gera uma sequencia de numeros
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#RESHAPE - define linhas e colunas
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
#colocar de 10 a 30 e de cinco a cinco(5)
np.arange(10,30,5)


array([10, 15, 20, 25])

In [29]:
#number flutuantes 
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [33]:
#LINSPACE - > define qtde de números
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

#OPERAÇÕES BÁSICAS 
#fonte: https://numpy.org/doc/stable/user/quickstart.html#basic-operations

In [41]:
a =np.array([20,30,40,50])
b =np.arange(4)
a

array([20, 30, 40, 50])

In [42]:
b

array([0, 1, 2, 3])

In [43]:
#Para cada indice ele irá fazer a subtração
a-b

array([20, 29, 38, 47])

In [44]:
#Realizando ao quadrado do b
b**2

array([0, 1, 4, 9], dtype=int32)

In [45]:
#Chamando o vetor dentro da função
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [47]:
#De forma booleana
a<25

array([ True, False, False, False])

In [50]:
#criando outras matrizes
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])


In [54]:
print('Matriz de A: ', A)
print('Matriz de B:' , B)

Matriz de A:  [[1 1]
 [0 1]]
Matriz de B: [[2 0]
 [3 4]]


In [55]:
#Multiplicando as matrizes temos o Produto Elementar
A * B

array([[2, 0],
       [0, 4]])

In [58]:
#Usando a função dot para o Produto Matricial
#Pode ser assim: A.dot(B)
#OR
np.dot(A,B)


array([[5, 4],
       [3, 4]])

In [78]:
#+= e *= atuam para modificar uma matriz existente em vez de criar uma nova
#Todos os elementos a serão somado mais 3
A +=3
A

array([[133, 129],
       [126, 137]])

In [64]:
A *=3
A

array([[126, 126],
       [117, 126]])

In [66]:
#somando respectivo as duas matrizes
A += B
A

array([[130, 126],
       [123, 134]])

In [67]:
#Retornando todos os somatórios
A.sum()


513

In [69]:
#retornando o menor(min) elemento ou o maior(max) elemento dentro da matriz
A.max()

134

In [73]:
#pegando o elemento por indice
A[1,1]

134

In [74]:
#os dois pontos signica um intervalo
A[:,0]

array([130, 123])

In [75]:
#Matriz Transposta
np.transpose(A)

array([[130, 123],
       [126, 134]])

In [76]:
B

array([[2, 0],
       [3, 4]])

In [77]:
np.transpose(B)

array([[2, 3],
       [0, 4]])